apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "892893225782.dkr.ecr.eu-west-1.amazonaws.com/myecrrepo:latest"
        command: ["gunicorn", "--bind", "0.0.0.0:5000", "manage:app"]
        ports:
        - containerPort: 5000
